// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/block_info_pb2/block_info.proto

package block_info_pb2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockInfoConfig struct {
	LatestBlock          uint64   `protobuf:"varint,1,opt,name=latest_block,json=latestBlock,proto3" json:"latest_block,omitempty"`
	OldestBlock          uint64   `protobuf:"varint,2,opt,name=oldest_block,json=oldestBlock,proto3" json:"oldest_block,omitempty"`
	TargetCount          uint64   `protobuf:"varint,3,opt,name=target_count,json=targetCount,proto3" json:"target_count,omitempty"`
	SyncTolerance        uint64   `protobuf:"varint,4,opt,name=sync_tolerance,json=syncTolerance,proto3" json:"sync_tolerance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockInfoConfig) Reset()         { *m = BlockInfoConfig{} }
func (m *BlockInfoConfig) String() string { return proto.CompactTextString(m) }
func (*BlockInfoConfig) ProtoMessage()    {}
func (*BlockInfoConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_af699305c755c0cd, []int{0}
}

func (m *BlockInfoConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInfoConfig.Unmarshal(m, b)
}
func (m *BlockInfoConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInfoConfig.Marshal(b, m, deterministic)
}
func (m *BlockInfoConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInfoConfig.Merge(m, src)
}
func (m *BlockInfoConfig) XXX_Size() int {
	return xxx_messageInfo_BlockInfoConfig.Size(m)
}
func (m *BlockInfoConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInfoConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInfoConfig proto.InternalMessageInfo

func (m *BlockInfoConfig) GetLatestBlock() uint64 {
	if m != nil {
		return m.LatestBlock
	}
	return 0
}

func (m *BlockInfoConfig) GetOldestBlock() uint64 {
	if m != nil {
		return m.OldestBlock
	}
	return 0
}

func (m *BlockInfoConfig) GetTargetCount() uint64 {
	if m != nil {
		return m.TargetCount
	}
	return 0
}

func (m *BlockInfoConfig) GetSyncTolerance() uint64 {
	if m != nil {
		return m.SyncTolerance
	}
	return 0
}

type BlockInfo struct {
	// Block number in the chain
	BlockNum uint64 `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	// The header_signature of the previous block that was added to the chain.
	PreviousBlockId string `protobuf:"bytes,2,opt,name=previous_block_id,json=previousBlockId,proto3" json:"previous_block_id,omitempty"`
	// Public key for the component internal to the validator that
	// signed the BlockHeader
	SignerPublicKey string `protobuf:"bytes,3,opt,name=signer_public_key,json=signerPublicKey,proto3" json:"signer_public_key,omitempty"`
	// The signature derived from signing the header
	HeaderSignature string `protobuf:"bytes,4,opt,name=header_signature,json=headerSignature,proto3" json:"header_signature,omitempty"`
	// Approximately when this block was committed, as a Unix UTC timestamp
	Timestamp            uint64   `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockInfo) Reset()         { *m = BlockInfo{} }
func (m *BlockInfo) String() string { return proto.CompactTextString(m) }
func (*BlockInfo) ProtoMessage()    {}
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_af699305c755c0cd, []int{1}
}

func (m *BlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInfo.Unmarshal(m, b)
}
func (m *BlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInfo.Marshal(b, m, deterministic)
}
func (m *BlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInfo.Merge(m, src)
}
func (m *BlockInfo) XXX_Size() int {
	return xxx_messageInfo_BlockInfo.Size(m)
}
func (m *BlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInfo proto.InternalMessageInfo

func (m *BlockInfo) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *BlockInfo) GetPreviousBlockId() string {
	if m != nil {
		return m.PreviousBlockId
	}
	return ""
}

func (m *BlockInfo) GetSignerPublicKey() string {
	if m != nil {
		return m.SignerPublicKey
	}
	return ""
}

func (m *BlockInfo) GetHeaderSignature() string {
	if m != nil {
		return m.HeaderSignature
	}
	return ""
}

func (m *BlockInfo) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BlockInfoTxn struct {
	// The new block to add to state
	Block *BlockInfo `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	// If this is set, the new target number of blocks to store in state
	TargetCount uint64 `protobuf:"varint,2,opt,name=target_count,json=targetCount,proto3" json:"target_count,omitempty"`
	// If set, the new network time synchronization tolerance.
	SyncTolerance        uint64   `protobuf:"varint,3,opt,name=sync_tolerance,json=syncTolerance,proto3" json:"sync_tolerance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockInfoTxn) Reset()         { *m = BlockInfoTxn{} }
func (m *BlockInfoTxn) String() string { return proto.CompactTextString(m) }
func (*BlockInfoTxn) ProtoMessage()    {}
func (*BlockInfoTxn) Descriptor() ([]byte, []int) {
	return fileDescriptor_af699305c755c0cd, []int{2}
}

func (m *BlockInfoTxn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInfoTxn.Unmarshal(m, b)
}
func (m *BlockInfoTxn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInfoTxn.Marshal(b, m, deterministic)
}
func (m *BlockInfoTxn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInfoTxn.Merge(m, src)
}
func (m *BlockInfoTxn) XXX_Size() int {
	return xxx_messageInfo_BlockInfoTxn.Size(m)
}
func (m *BlockInfoTxn) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInfoTxn.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInfoTxn proto.InternalMessageInfo

func (m *BlockInfoTxn) GetBlock() *BlockInfo {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockInfoTxn) GetTargetCount() uint64 {
	if m != nil {
		return m.TargetCount
	}
	return 0
}

func (m *BlockInfoTxn) GetSyncTolerance() uint64 {
	if m != nil {
		return m.SyncTolerance
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockInfoConfig)(nil), "BlockInfoConfig")
	proto.RegisterType((*BlockInfo)(nil), "BlockInfo")
	proto.RegisterType((*BlockInfoTxn)(nil), "BlockInfoTxn")
}

func init() {
	proto.RegisterFile("protobuf/block_info_pb2/block_info.proto", fileDescriptor_af699305c755c0cd)
}

var fileDescriptor_af699305c755c0cd = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0x49, 0x7f, 0x3e, 0xbe, 0x9c, 0xd6, 0x46, 0x67, 0x15, 0xb0, 0x8b, 0x5a, 0x10, 0xaa,
	0x8b, 0x2a, 0xf5, 0x0e, 0xda, 0x95, 0x08, 0x52, 0x62, 0x57, 0x6e, 0x86, 0x49, 0x32, 0x69, 0x43,
	0x93, 0x99, 0x30, 0x39, 0xa3, 0xd6, 0xbb, 0xf1, 0x72, 0xbc, 0x2b, 0xc9, 0x4c, 0x9b, 0xf8, 0xb7,
	0x70, 0x99, 0xe7, 0x7d, 0x08, 0xef, 0x79, 0x19, 0x98, 0x14, 0x4a, 0xa2, 0x0c, 0x75, 0x72, 0x15,
	0x66, 0x32, 0xda, 0xd2, 0x54, 0x24, 0x92, 0x16, 0xe1, 0xec, 0xd3, 0xe7, 0xd4, 0x28, 0xe3, 0x37,
	0x07, 0xbc, 0x79, 0x05, 0x6f, 0x45, 0x22, 0x17, 0x52, 0x24, 0xe9, 0x9a, 0x9c, 0x41, 0x3f, 0x63,
	0xc8, 0x4b, 0xa4, 0x46, 0xf7, 0x9d, 0x91, 0x33, 0xe9, 0x04, 0x3d, 0xcb, 0x8c, 0x5c, 0x29, 0x32,
	0x8b, 0x1b, 0xa5, 0x65, 0x15, 0xcb, 0x6a, 0x05, 0x99, 0x5a, 0x73, 0xa4, 0x91, 0xd4, 0x02, 0xfd,
	0xb6, 0x55, 0x2c, 0x5b, 0x54, 0x88, 0x9c, 0xc3, 0xa0, 0xdc, 0x89, 0x88, 0xa2, 0xcc, 0xb8, 0x62,
	0x22, 0xe2, 0x7e, 0xc7, 0x48, 0x47, 0x15, 0x5d, 0x1d, 0xe0, 0xf8, 0xdd, 0x01, 0xb7, 0xee, 0x48,
	0x4e, 0xc1, 0xb5, 0x57, 0x08, 0x9d, 0xef, 0xab, 0xfd, 0x37, 0xe0, 0x5e, 0xe7, 0xe4, 0x12, 0x4e,
	0x0a, 0xc5, 0x9f, 0x52, 0xa9, 0x4b, 0xba, 0xbf, 0x35, 0x36, 0xe5, 0xdc, 0xc0, 0x3b, 0x04, 0xf6,
	0x57, 0x71, 0xe5, 0x96, 0xe9, 0x5a, 0x70, 0x45, 0x0b, 0x1d, 0x66, 0x69, 0x44, 0xb7, 0x7c, 0x67,
	0x5a, 0xba, 0x81, 0x67, 0x83, 0xa5, 0xe1, 0x77, 0x7c, 0x47, 0x2e, 0xe0, 0x78, 0xc3, 0x59, 0xcc,
	0x15, 0xad, 0x12, 0x86, 0x5a, 0xd9, 0xae, 0x6e, 0xe0, 0x59, 0xfe, 0x70, 0xc0, 0x64, 0x08, 0x2e,
	0xa6, 0x39, 0x2f, 0x91, 0xe5, 0x85, 0xdf, 0x35, 0xfd, 0x1a, 0x30, 0x7e, 0x85, 0x7e, 0x7d, 0xca,
	0xea, 0x45, 0x90, 0x11, 0x74, 0x9b, 0x91, 0x7b, 0x33, 0x98, 0xd6, 0x69, 0x60, 0x83, 0x1f, 0x3b,
	0xb6, 0xfe, 0xb2, 0x63, 0xfb, 0x97, 0x1d, 0xe7, 0xd7, 0x30, 0x2c, 0xd9, 0x33, 0x4a, 0x89, 0x9b,
	0xe9, 0xf7, 0x87, 0x10, 0xea, 0x64, 0xe9, 0x3c, 0x0e, 0xbe, 0x3e, 0x97, 0xf0, 0x9f, 0xc9, 0x6e,
	0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x50, 0x6a, 0x84, 0xf7, 0x50, 0x02, 0x00, 0x00,
}
