// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/seth_pb2/seth.proto

package seth_pb2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SethTransaction_TransactionType int32

const (
	SethTransaction_TRANSACTION_TYPE_UNSET  SethTransaction_TransactionType = 0
	SethTransaction_CREATE_EXTERNAL_ACCOUNT SethTransaction_TransactionType = 1
	SethTransaction_CREATE_CONTRACT_ACCOUNT SethTransaction_TransactionType = 2
	SethTransaction_MESSAGE_CALL            SethTransaction_TransactionType = 3
	SethTransaction_SET_PERMISSIONS         SethTransaction_TransactionType = 4
)

var SethTransaction_TransactionType_name = map[int32]string{
	0: "TRANSACTION_TYPE_UNSET",
	1: "CREATE_EXTERNAL_ACCOUNT",
	2: "CREATE_CONTRACT_ACCOUNT",
	3: "MESSAGE_CALL",
	4: "SET_PERMISSIONS",
}

var SethTransaction_TransactionType_value = map[string]int32{
	"TRANSACTION_TYPE_UNSET":  0,
	"CREATE_EXTERNAL_ACCOUNT": 1,
	"CREATE_CONTRACT_ACCOUNT": 2,
	"MESSAGE_CALL":            3,
	"SET_PERMISSIONS":         4,
}

func (x SethTransaction_TransactionType) String() string {
	return proto.EnumName(SethTransaction_TransactionType_name, int32(x))
}

func (SethTransaction_TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dc8fa5936fdae092, []int{4, 0}
}

type EvmEntry struct {
	Account              *EvmStateAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Storage              []*EvmStorage    `protobuf:"bytes,2,rep,name=storage,proto3" json:"storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EvmEntry) Reset()         { *m = EvmEntry{} }
func (m *EvmEntry) String() string { return proto.CompactTextString(m) }
func (*EvmEntry) ProtoMessage()    {}
func (*EvmEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc8fa5936fdae092, []int{0}
}

func (m *EvmEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmEntry.Unmarshal(m, b)
}
func (m *EvmEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmEntry.Marshal(b, m, deterministic)
}
func (m *EvmEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmEntry.Merge(m, src)
}
func (m *EvmEntry) XXX_Size() int {
	return xxx_messageInfo_EvmEntry.Size(m)
}
func (m *EvmEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmEntry.DiscardUnknown(m)
}

var xxx_messageInfo_EvmEntry proto.InternalMessageInfo

func (m *EvmEntry) GetAccount() *EvmStateAccount {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *EvmEntry) GetStorage() []*EvmStorage {
	if m != nil {
		return m.Storage
	}
	return nil
}

type EvmStateAccount struct {
	Address              []byte          `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance              int64           `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Code                 []byte          `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Nonce                uint64          `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Permissions          *EvmPermissions `protobuf:"bytes,5,opt,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EvmStateAccount) Reset()         { *m = EvmStateAccount{} }
func (m *EvmStateAccount) String() string { return proto.CompactTextString(m) }
func (*EvmStateAccount) ProtoMessage()    {}
func (*EvmStateAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc8fa5936fdae092, []int{1}
}

func (m *EvmStateAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmStateAccount.Unmarshal(m, b)
}
func (m *EvmStateAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmStateAccount.Marshal(b, m, deterministic)
}
func (m *EvmStateAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmStateAccount.Merge(m, src)
}
func (m *EvmStateAccount) XXX_Size() int {
	return xxx_messageInfo_EvmStateAccount.Size(m)
}
func (m *EvmStateAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmStateAccount.DiscardUnknown(m)
}

var xxx_messageInfo_EvmStateAccount proto.InternalMessageInfo

func (m *EvmStateAccount) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *EvmStateAccount) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *EvmStateAccount) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *EvmStateAccount) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *EvmStateAccount) GetPermissions() *EvmPermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type EvmPermissions struct {
	// Bit array where true means "has permission" and false means "doesn't have
	// permission"
	Perms uint64 `protobuf:"varint,1,opt,name=perms,proto3" json:"perms,omitempty"`
	// Bit array where true means "the permission has been set" and false means
	// "the permission has not been set".
	SetBit               uint64   `protobuf:"varint,2,opt,name=set_bit,json=setBit,proto3" json:"set_bit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmPermissions) Reset()         { *m = EvmPermissions{} }
func (m *EvmPermissions) String() string { return proto.CompactTextString(m) }
func (*EvmPermissions) ProtoMessage()    {}
func (*EvmPermissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc8fa5936fdae092, []int{2}
}

func (m *EvmPermissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmPermissions.Unmarshal(m, b)
}
func (m *EvmPermissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmPermissions.Marshal(b, m, deterministic)
}
func (m *EvmPermissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmPermissions.Merge(m, src)
}
func (m *EvmPermissions) XXX_Size() int {
	return xxx_messageInfo_EvmPermissions.Size(m)
}
func (m *EvmPermissions) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmPermissions.DiscardUnknown(m)
}

var xxx_messageInfo_EvmPermissions proto.InternalMessageInfo

func (m *EvmPermissions) GetPerms() uint64 {
	if m != nil {
		return m.Perms
	}
	return 0
}

func (m *EvmPermissions) GetSetBit() uint64 {
	if m != nil {
		return m.SetBit
	}
	return 0
}

type EvmStorage struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmStorage) Reset()         { *m = EvmStorage{} }
func (m *EvmStorage) String() string { return proto.CompactTextString(m) }
func (*EvmStorage) ProtoMessage()    {}
func (*EvmStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc8fa5936fdae092, []int{3}
}

func (m *EvmStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmStorage.Unmarshal(m, b)
}
func (m *EvmStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmStorage.Marshal(b, m, deterministic)
}
func (m *EvmStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmStorage.Merge(m, src)
}
func (m *EvmStorage) XXX_Size() int {
	return xxx_messageInfo_EvmStorage.Size(m)
}
func (m *EvmStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmStorage.DiscardUnknown(m)
}

var xxx_messageInfo_EvmStorage proto.InternalMessageInfo

func (m *EvmStorage) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *EvmStorage) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SethTransaction struct {
	TransactionType SethTransaction_TransactionType `protobuf:"varint,1,opt,name=transaction_type,json=transactionType,proto3,enum=SethTransaction_TransactionType" json:"transaction_type,omitempty"`
	// To eliminate the need for two deserialization steps, all types of
	// transactions are included as fields, but only the field indicated by the
	// transaction type should be set.
	CreateExternalAccount *CreateExternalAccountTxn `protobuf:"bytes,2,opt,name=create_external_account,json=createExternalAccount,proto3" json:"create_external_account,omitempty"`
	CreateContractAccount *CreateContractAccountTxn `protobuf:"bytes,3,opt,name=create_contract_account,json=createContractAccount,proto3" json:"create_contract_account,omitempty"`
	MessageCall           *MessageCallTxn           `protobuf:"bytes,4,opt,name=message_call,json=messageCall,proto3" json:"message_call,omitempty"`
	SetPermissions        *SetPermissionsTxn        `protobuf:"bytes,5,opt,name=set_permissions,json=setPermissions,proto3" json:"set_permissions,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                  `json:"-"`
	XXX_unrecognized      []byte                    `json:"-"`
	XXX_sizecache         int32                     `json:"-"`
}

func (m *SethTransaction) Reset()         { *m = SethTransaction{} }
func (m *SethTransaction) String() string { return proto.CompactTextString(m) }
func (*SethTransaction) ProtoMessage()    {}
func (*SethTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc8fa5936fdae092, []int{4}
}

func (m *SethTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SethTransaction.Unmarshal(m, b)
}
func (m *SethTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SethTransaction.Marshal(b, m, deterministic)
}
func (m *SethTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SethTransaction.Merge(m, src)
}
func (m *SethTransaction) XXX_Size() int {
	return xxx_messageInfo_SethTransaction.Size(m)
}
func (m *SethTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_SethTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_SethTransaction proto.InternalMessageInfo

func (m *SethTransaction) GetTransactionType() SethTransaction_TransactionType {
	if m != nil {
		return m.TransactionType
	}
	return SethTransaction_TRANSACTION_TYPE_UNSET
}

func (m *SethTransaction) GetCreateExternalAccount() *CreateExternalAccountTxn {
	if m != nil {
		return m.CreateExternalAccount
	}
	return nil
}

func (m *SethTransaction) GetCreateContractAccount() *CreateContractAccountTxn {
	if m != nil {
		return m.CreateContractAccount
	}
	return nil
}

func (m *SethTransaction) GetMessageCall() *MessageCallTxn {
	if m != nil {
		return m.MessageCall
	}
	return nil
}

func (m *SethTransaction) GetSetPermissions() *SetPermissionsTxn {
	if m != nil {
		return m.SetPermissions
	}
	return nil
}

type CreateExternalAccountTxn struct {
	// "...the number of transactions sent by the sender; formally T_n."
	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// "...the 160-bit address of the message call's recipient or, for a
	// contract creation transaction, ∅, used here to denote (the empty byte
	// array); formally T_t."
	To []byte `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// The Burrow-EVM permissions to assign to the new account
	Permissions          *EvmPermissions `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateExternalAccountTxn) Reset()         { *m = CreateExternalAccountTxn{} }
func (m *CreateExternalAccountTxn) String() string { return proto.CompactTextString(m) }
func (*CreateExternalAccountTxn) ProtoMessage()    {}
func (*CreateExternalAccountTxn) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc8fa5936fdae092, []int{5}
}

func (m *CreateExternalAccountTxn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateExternalAccountTxn.Unmarshal(m, b)
}
func (m *CreateExternalAccountTxn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateExternalAccountTxn.Marshal(b, m, deterministic)
}
func (m *CreateExternalAccountTxn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateExternalAccountTxn.Merge(m, src)
}
func (m *CreateExternalAccountTxn) XXX_Size() int {
	return xxx_messageInfo_CreateExternalAccountTxn.Size(m)
}
func (m *CreateExternalAccountTxn) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateExternalAccountTxn.DiscardUnknown(m)
}

var xxx_messageInfo_CreateExternalAccountTxn proto.InternalMessageInfo

func (m *CreateExternalAccountTxn) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *CreateExternalAccountTxn) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *CreateExternalAccountTxn) GetPermissions() *EvmPermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type CreateContractAccountTxn struct {
	// "...the number of transactions sent by the sender; formally T_n."
	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// "...the number of Wei to be paid per unit of gas for all computation
	// costs incurred as a result of the execution of this transaction;
	// formally T_p."
	GasPrice uint64 `protobuf:"varint,2,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// "...the maximum amount of gas that should be used in executing this
	// transaction. This is paid up-front, before any computation is done and
	// may not be increased later; formally T_g"
	GasLimit uint64 `protobuf:"varint,3,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// "...the number of Wei to be transferred to the message call's recipient
	// or, in the case of contract creation, as an endowment to the newly
	// created account; formally T_v."
	Value uint64 `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	// "An unlimited size byte array specifying the EVM-code for the account
	// initialisation procedure, formally T_i."
	//
	// This should only be set if this is a contract creation transaction.
	Init []byte `protobuf:"bytes,5,opt,name=init,proto3" json:"init,omitempty"`
	// The Burrow-EVM permissions to assign to this account
	Permissions          *EvmPermissions `protobuf:"bytes,6,opt,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateContractAccountTxn) Reset()         { *m = CreateContractAccountTxn{} }
func (m *CreateContractAccountTxn) String() string { return proto.CompactTextString(m) }
func (*CreateContractAccountTxn) ProtoMessage()    {}
func (*CreateContractAccountTxn) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc8fa5936fdae092, []int{6}
}

func (m *CreateContractAccountTxn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContractAccountTxn.Unmarshal(m, b)
}
func (m *CreateContractAccountTxn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContractAccountTxn.Marshal(b, m, deterministic)
}
func (m *CreateContractAccountTxn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContractAccountTxn.Merge(m, src)
}
func (m *CreateContractAccountTxn) XXX_Size() int {
	return xxx_messageInfo_CreateContractAccountTxn.Size(m)
}
func (m *CreateContractAccountTxn) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContractAccountTxn.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContractAccountTxn proto.InternalMessageInfo

func (m *CreateContractAccountTxn) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *CreateContractAccountTxn) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *CreateContractAccountTxn) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *CreateContractAccountTxn) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *CreateContractAccountTxn) GetInit() []byte {
	if m != nil {
		return m.Init
	}
	return nil
}

func (m *CreateContractAccountTxn) GetPermissions() *EvmPermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type MessageCallTxn struct {
	// "...the number of transactions sent by the sender; formally T_n."
	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// "...the number of Wei to be paid per unit of gas for all computation
	// costs incurred as a result of the execution of this transaction;
	// formally T_p."
	GasPrice uint64 `protobuf:"varint,2,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// "...the maximum amount of gas that should be used in executing this
	// transaction. This is paid up-front, before any computation is done and
	// may not be increased later; formally T_g"
	GasLimit uint64 `protobuf:"varint,3,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// "...the 160-bit address of the message call's recipient or, for a
	// contract creation transaction, ∅, used here to denote (the empty byte
	// array); formally T_t."
	To []byte `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	// "...the number of Wei to be transferred to the message call's recipient
	// or, in the case of contract creation, as an endowment to the newly
	// created account; formally T_v."
	Value uint64 `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	// "An unlimited size byte array specifying the input data of the message
	// call, formally T_d."
	//
	// This should only be set if this is a message call transaction.
	Data                 []byte   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageCallTxn) Reset()         { *m = MessageCallTxn{} }
func (m *MessageCallTxn) String() string { return proto.CompactTextString(m) }
func (*MessageCallTxn) ProtoMessage()    {}
func (*MessageCallTxn) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc8fa5936fdae092, []int{7}
}

func (m *MessageCallTxn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageCallTxn.Unmarshal(m, b)
}
func (m *MessageCallTxn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageCallTxn.Marshal(b, m, deterministic)
}
func (m *MessageCallTxn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageCallTxn.Merge(m, src)
}
func (m *MessageCallTxn) XXX_Size() int {
	return xxx_messageInfo_MessageCallTxn.Size(m)
}
func (m *MessageCallTxn) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageCallTxn.DiscardUnknown(m)
}

var xxx_messageInfo_MessageCallTxn proto.InternalMessageInfo

func (m *MessageCallTxn) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MessageCallTxn) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *MessageCallTxn) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *MessageCallTxn) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *MessageCallTxn) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *MessageCallTxn) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SetPermissionsTxn struct {
	// "...the number of transactions sent by the sender; formally T_n."
	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// "...the 160-bit address of the message call's recipient or, for a
	// contract creation transaction, ∅, used here to denote (the empty byte
	// array); formally T_t."
	To []byte `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// The Burrow-EVM permissions to assign to this account
	Permissions          *EvmPermissions `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SetPermissionsTxn) Reset()         { *m = SetPermissionsTxn{} }
func (m *SetPermissionsTxn) String() string { return proto.CompactTextString(m) }
func (*SetPermissionsTxn) ProtoMessage()    {}
func (*SetPermissionsTxn) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc8fa5936fdae092, []int{8}
}

func (m *SetPermissionsTxn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPermissionsTxn.Unmarshal(m, b)
}
func (m *SetPermissionsTxn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPermissionsTxn.Marshal(b, m, deterministic)
}
func (m *SetPermissionsTxn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPermissionsTxn.Merge(m, src)
}
func (m *SetPermissionsTxn) XXX_Size() int {
	return xxx_messageInfo_SetPermissionsTxn.Size(m)
}
func (m *SetPermissionsTxn) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPermissionsTxn.DiscardUnknown(m)
}

var xxx_messageInfo_SetPermissionsTxn proto.InternalMessageInfo

func (m *SetPermissionsTxn) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *SetPermissionsTxn) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *SetPermissionsTxn) GetPermissions() *EvmPermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type SethTransactionReceipt struct {
	ContractAddress      []byte   `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	GasUsed              uint64   `protobuf:"varint,2,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	ReturnValue          []byte   `protobuf:"bytes,3,opt,name=return_value,json=returnValue,proto3" json:"return_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SethTransactionReceipt) Reset()         { *m = SethTransactionReceipt{} }
func (m *SethTransactionReceipt) String() string { return proto.CompactTextString(m) }
func (*SethTransactionReceipt) ProtoMessage()    {}
func (*SethTransactionReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc8fa5936fdae092, []int{9}
}

func (m *SethTransactionReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SethTransactionReceipt.Unmarshal(m, b)
}
func (m *SethTransactionReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SethTransactionReceipt.Marshal(b, m, deterministic)
}
func (m *SethTransactionReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SethTransactionReceipt.Merge(m, src)
}
func (m *SethTransactionReceipt) XXX_Size() int {
	return xxx_messageInfo_SethTransactionReceipt.Size(m)
}
func (m *SethTransactionReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_SethTransactionReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_SethTransactionReceipt proto.InternalMessageInfo

func (m *SethTransactionReceipt) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *SethTransactionReceipt) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *SethTransactionReceipt) GetReturnValue() []byte {
	if m != nil {
		return m.ReturnValue
	}
	return nil
}

type EvmLogData struct {
	// 20 Bytes - address from which this log originated.
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Array of 0 to 4 32-byte blobs of data.
	// (In solidity: The first topic is the hash of the signature
	// of the event (e.g. Deposit(address,bytes32,uint256)), except
	// you declared the event with the 'anonymous' specifier.)
	// See the following:
	// https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterchanges
	Topics [][]byte `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	// contains one or more 32 Bytes non-indexed arguments of the log.
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvmLogData) Reset()         { *m = EvmLogData{} }
func (m *EvmLogData) String() string { return proto.CompactTextString(m) }
func (*EvmLogData) ProtoMessage()    {}
func (*EvmLogData) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc8fa5936fdae092, []int{10}
}

func (m *EvmLogData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvmLogData.Unmarshal(m, b)
}
func (m *EvmLogData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvmLogData.Marshal(b, m, deterministic)
}
func (m *EvmLogData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvmLogData.Merge(m, src)
}
func (m *EvmLogData) XXX_Size() int {
	return xxx_messageInfo_EvmLogData.Size(m)
}
func (m *EvmLogData) XXX_DiscardUnknown() {
	xxx_messageInfo_EvmLogData.DiscardUnknown(m)
}

var xxx_messageInfo_EvmLogData proto.InternalMessageInfo

func (m *EvmLogData) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *EvmLogData) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *EvmLogData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("SethTransaction_TransactionType", SethTransaction_TransactionType_name, SethTransaction_TransactionType_value)
	proto.RegisterType((*EvmEntry)(nil), "EvmEntry")
	proto.RegisterType((*EvmStateAccount)(nil), "EvmStateAccount")
	proto.RegisterType((*EvmPermissions)(nil), "EvmPermissions")
	proto.RegisterType((*EvmStorage)(nil), "EvmStorage")
	proto.RegisterType((*SethTransaction)(nil), "SethTransaction")
	proto.RegisterType((*CreateExternalAccountTxn)(nil), "CreateExternalAccountTxn")
	proto.RegisterType((*CreateContractAccountTxn)(nil), "CreateContractAccountTxn")
	proto.RegisterType((*MessageCallTxn)(nil), "MessageCallTxn")
	proto.RegisterType((*SetPermissionsTxn)(nil), "SetPermissionsTxn")
	proto.RegisterType((*SethTransactionReceipt)(nil), "SethTransactionReceipt")
	proto.RegisterType((*EvmLogData)(nil), "EvmLogData")
}

func init() { proto.RegisterFile("protobuf/seth_pb2/seth.proto", fileDescriptor_dc8fa5936fdae092) }

var fileDescriptor_dc8fa5936fdae092 = []byte{
	// 755 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0xc6, 0xb1, 0x9b, 0x94, 0x17, 0x2b, 0x36, 0x03, 0xb4, 0x29, 0xe5, 0x10, 0x2c, 0x21, 0x05,
	0x0e, 0x41, 0x04, 0x6e, 0x1c, 0x90, 0x6b, 0x2c, 0x54, 0x91, 0x26, 0x61, 0xec, 0x22, 0x40, 0x42,
	0xd6, 0xc4, 0x19, 0x52, 0x6b, 0x1d, 0xdb, 0xf2, 0x4c, 0xaa, 0xe6, 0xb8, 0x97, 0x3d, 0xee, 0x0f,
	0xd8, 0xe3, 0xfe, 0x99, 0xfd, 0x5b, 0xab, 0x19, 0xdb, 0x71, 0xe2, 0x6c, 0x57, 0x3d, 0xec, 0xde,
	0xde, 0xf7, 0xbe, 0xe7, 0xe7, 0x79, 0xef, 0x7b, 0xf3, 0x06, 0xbe, 0xce, 0xf2, 0x94, 0xa7, 0x8b,
	0xcd, 0xff, 0x3f, 0x30, 0xca, 0xef, 0x82, 0x6c, 0x31, 0x96, 0xc6, 0x48, 0xba, 0xad, 0xff, 0xe0,
	0xd4, 0xbd, 0x5f, 0xbb, 0x09, 0xcf, 0xb7, 0xe8, 0x7b, 0xe8, 0x90, 0x30, 0x4c, 0x37, 0x09, 0xef,
	0x2b, 0x03, 0x65, 0xd8, 0x1d, 0x9b, 0x23, 0xf7, 0x7e, 0xed, 0x71, 0xc2, 0xa9, 0x5d, 0xf8, 0x71,
	0x15, 0x80, 0xbe, 0x85, 0x0e, 0xe3, 0x69, 0x4e, 0x56, 0xb4, 0xdf, 0x1a, 0xa8, 0xc3, 0xee, 0xb8,
	0x5b, 0xc4, 0x4a, 0x17, 0xae, 0x38, 0xeb, 0xb5, 0x02, 0x46, 0x23, 0x07, 0xea, 0x43, 0x87, 0x2c,
	0x97, 0x39, 0x65, 0x4c, 0xfe, 0x46, 0xc7, 0x15, 0x14, 0xcc, 0x82, 0xc4, 0x24, 0x09, 0x45, 0x52,
	0x65, 0xa8, 0xe2, 0x0a, 0x22, 0x04, 0x5a, 0x98, 0x2e, 0x69, 0x5f, 0x95, 0x1f, 0x48, 0x1b, 0x7d,
	0x01, 0x27, 0x49, 0x2a, 0x62, 0xb5, 0x81, 0x32, 0xd4, 0x70, 0x01, 0xd0, 0x8f, 0xd0, 0xcd, 0x68,
	0xbe, 0x8e, 0x18, 0x8b, 0xd2, 0x84, 0xf5, 0x4f, 0x64, 0x21, 0x86, 0x38, 0xdc, 0xbc, 0x76, 0xe3,
	0xfd, 0x18, 0xeb, 0x57, 0xe8, 0x1d, 0xd2, 0x22, 0xb5, 0x08, 0x28, 0x0e, 0xa8, 0xe1, 0x02, 0xa0,
	0x73, 0xe8, 0x30, 0xca, 0x83, 0x45, 0xc4, 0xe5, 0xf1, 0x34, 0xdc, 0x66, 0x94, 0x5f, 0x45, 0xdc,
	0xfa, 0x19, 0xa0, 0x2e, 0x1e, 0x99, 0xa0, 0x3e, 0xa3, 0xdb, 0xb2, 0x36, 0x61, 0x8a, 0x74, 0xf7,
	0x24, 0xde, 0x14, 0x55, 0xe9, 0xb8, 0x00, 0xd6, 0x0b, 0x0d, 0x0c, 0x8f, 0xf2, 0x3b, 0x3f, 0x27,
	0x09, 0x23, 0x21, 0x8f, 0xd2, 0x04, 0xfd, 0x01, 0x26, 0xaf, 0x61, 0xc0, 0xb7, 0x19, 0x95, 0x89,
	0x7a, 0xe3, 0xc1, 0xa8, 0x11, 0x3b, 0xda, 0xb3, 0xfd, 0x6d, 0x46, 0xb1, 0xc1, 0x0f, 0x1d, 0xe8,
	0x4f, 0x38, 0x0f, 0x73, 0x4a, 0x38, 0x0d, 0xe8, 0x03, 0xa7, 0x79, 0x42, 0xe2, 0xa0, 0xd2, 0xb7,
	0x25, 0xdb, 0x72, 0x31, 0x72, 0x24, 0xef, 0x96, 0x74, 0xa9, 0x90, 0xff, 0x90, 0xe0, 0x2f, 0xc3,
	0x77, 0x31, 0x7b, 0x29, 0xc3, 0x34, 0xe1, 0x39, 0x09, 0xf9, 0x2e, 0xa5, 0x7a, 0x90, 0xd2, 0x29,
	0xe9, 0xe3, 0x94, 0x0d, 0x06, 0x8d, 0x41, 0x5f, 0x53, 0xc6, 0xc8, 0x8a, 0x06, 0x21, 0x89, 0x63,
	0xa9, 0xa6, 0x50, 0xec, 0xa6, 0x70, 0x3a, 0x24, 0x8e, 0xc5, 0xd7, 0xdd, 0x75, 0x8d, 0xd1, 0x2f,
	0x60, 0x08, 0x25, 0x8e, 0x85, 0x46, 0xa2, 0x4b, 0x7b, 0x4a, 0x8a, 0x2f, 0x7b, 0xec, 0xc0, 0x65,
	0xbd, 0x54, 0xc0, 0x68, 0xf4, 0x0e, 0x7d, 0x05, 0x67, 0x3e, 0xb6, 0xa7, 0x9e, 0xed, 0xf8, 0xd7,
	0xb3, 0x69, 0xe0, 0xff, 0x33, 0x77, 0x83, 0xdb, 0xa9, 0xe7, 0xfa, 0xe6, 0x27, 0xe8, 0x12, 0xce,
	0x1d, 0xec, 0xda, 0xbe, 0x1b, 0xb8, 0x7f, 0xfb, 0x2e, 0x9e, 0xda, 0x93, 0xc0, 0x76, 0x9c, 0xd9,
	0xed, 0xd4, 0x37, 0x95, 0x3d, 0xd2, 0x99, 0x4d, 0x7d, 0x6c, 0x3b, 0xfe, 0x8e, 0x6c, 0x21, 0x13,
	0xf4, 0x1b, 0xd7, 0xf3, 0xec, 0xdf, 0xdd, 0xc0, 0xb1, 0x27, 0x13, 0x53, 0x45, 0x9f, 0x83, 0xe1,
	0xb9, 0x7e, 0x30, 0x77, 0xf1, 0xcd, 0xb5, 0xe7, 0x5d, 0xcf, 0xa6, 0x9e, 0xa9, 0x59, 0x0c, 0xfa,
	0x8f, 0xe9, 0x50, 0x0f, 0xb9, 0xb2, 0x3f, 0xe4, 0x3d, 0x68, 0xf1, 0xb4, 0x9c, 0xa6, 0x16, 0x4f,
	0x9b, 0x43, 0xaf, 0x3e, 0x61, 0xe8, 0xdf, 0x28, 0xd5, 0x5f, 0x8f, 0xa5, 0x7a, 0xe4, 0xaf, 0x97,
	0xf0, 0xe9, 0x8a, 0xb0, 0x20, 0xcb, 0xa3, 0xf2, 0x82, 0x6a, 0xf8, 0x74, 0x45, 0xd8, 0x5c, 0xe0,
	0x8a, 0x8c, 0xa3, 0x75, 0x54, 0xcc, 0x42, 0x41, 0x4e, 0x04, 0xae, 0x2f, 0x40, 0x79, 0x55, 0x25,
	0x10, 0x97, 0x3a, 0x4a, 0x22, 0x2e, 0xa5, 0xd3, 0xb1, 0xb4, 0x9b, 0x95, 0xb4, 0x9f, 0x50, 0xc9,
	0x2b, 0x05, 0x7a, 0x87, 0xc3, 0xf2, 0xc1, 0xcf, 0x5f, 0xf4, 0x5b, 0xdb, 0xf5, 0x7b, 0x57, 0xcf,
	0x49, 0xa3, 0x9e, 0x25, 0xe1, 0x44, 0x1e, 0x5a, 0xc7, 0xd2, 0xb6, 0x62, 0xf8, 0xec, 0x68, 0x22,
	0x3f, 0x9e, 0xa8, 0xcf, 0x15, 0x38, 0x6b, 0xac, 0x09, 0x4c, 0x43, 0x1a, 0x65, 0x1c, 0x7d, 0x07,
	0x66, 0x7d, 0x65, 0x0f, 0xd6, 0xaf, 0x51, 0xf9, 0xed, 0x72, 0x0d, 0x5f, 0x80, 0xa8, 0x3c, 0xd8,
	0x30, 0xba, 0x2c, 0xdb, 0xd4, 0x59, 0x11, 0x76, 0xcb, 0xe8, 0x12, 0x7d, 0x03, 0x7a, 0x4e, 0xf9,
	0x26, 0x4f, 0x82, 0xa2, 0xfe, 0x62, 0x1f, 0x77, 0x0b, 0xdf, 0x5f, 0x72, 0xad, 0x61, 0xb9, 0x0c,
	0x27, 0xe9, 0xea, 0x37, 0xc2, 0xc9, 0x7b, 0x96, 0xfd, 0x19, 0xb4, 0x79, 0x9a, 0x45, 0x21, 0x93,
	0x0f, 0x88, 0x8e, 0x4b, 0xb4, 0xeb, 0xa2, 0x5a, 0x77, 0xf1, 0x0a, 0xfe, 0x3d, 0xad, 0x1e, 0xaf,
	0x45, 0x5b, 0x3e, 0x5c, 0x3f, 0xbd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x42, 0xd2, 0xdc, 0xd8,
	0x06, 0x00, 0x00,
}
